config/routes.rb
Foodee::Application.routes.draw do
  resources :recommendations do
    get "friendProfile"
    get "newsFeed"
  end

  resources :restaurants do

  end

  devise_for :users, :controllers => {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users do
    resources :addresses
    resources :recommendations
  end

  resources :home

  get "restaurants/recommendations"
  get "passthrough/index"
  get "welcome/index"
  get "home/index"

  root 'welcome#index'

end

app/models/recommendation.rb
class Recommendation < ActiveRecord::Base
  belongs_to :user
  belongs_to :restaurant

  # for paperclip
  # This method associates the attribute ":pictures" with a file attachment
  has_attached_file :pictures,
  styles: {
    thumb: '100x100>',
    square: '200x200#',
    medium: '300x300>'
  },
  :storage => :s3,
  :bucket => ENV['AWS_BUCKET'],
  :s3_credentials => {
    :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
    :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
  }

  # Validate the attached image is image/jpg, image/png, etc
  validates_attachment_content_type :pictures, :content_type => /\Aimage\/.*\Z/

  def self.get_friend_recommedation_by_restaurant(google_id, friend_id)
  	recommendation = Recommendation.where(user_id: User.select("id").where(id: friend_id),
  		restaurant_id: Restaurant.select("id").where(google_id: google_id))
    recommendation

  end

  def self.get_friend_recommedations(friends)
    recommendation = Recommendation.where(user_id: User.select("id").where(id: friends))
    recommendation
  end

  def self.get_my_recommedation(id)
    recommendation = Recommendation.where(user_id: id)
    recommendation
  end

  def self.get_my_recommedation_by_restaurant(user_id, google_id)
    recommendation = Recommendation.where(user_id: user_id, restaurant_id: Restaurant.select("id").where(google_id: google_id))
    recommendation
  end

end

app/controllers/recommendations_controller.rb
class RecommendationsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_recommendation, only: [:edit, :update, :destroy]
  before_action :set_friends, only: [:show, :newsFeed]

  # GET /recommendations
  # GET /recommendations.json
  def index
    @recommendations = Recommendation.get_my_recommedation(current_user.id)
  end

  # GET /recommendations/1
  # GET /recommendations/1.json
  def show
    @recommendations = Recommendation.get_friend_recommedation_by_restaurant(params[:restaurant_id], @registered_friends)
    @friend_recommendations = []
    @recommendations.each do |recommendation|
      friend = User.find(recommendation.user)
      hash = {:name => friend.full_name, :fb_id => friend.identity.uid, :image => @graph.get_picture(friend.identity.uid)}
      @friend_recommendations.push(hash)
    end

    # adding yelp reviews
    recommendation = Recommendation.where(:id => params[:id]).first

    # @restaurant = Restaurant.get_restaurant_by_yelp_id recommendation.restaurant.yelp_id
    # @reviews = @restaurant["reviews"]
    @reviews = Restaurant.get_restaurant_reviews_from_yelp recommendation.restaurant.yelp_id
    
    #@venue = Restaurant.get_venue_by_foursquare_id recommendation.restaurant.foursquare_id
    #@tips = Restaurant.get_venue_tips_from_foursquare recommendation.restaurant.foursquare_id
    @tips = Restaurant.get_venue_tips_from_foursquare recommendation.restaurant.foursquare_id

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /recommendations/new
  def new
    @recommendation = current_user.recommendations.build
  end

  # GET /recommendations/1/edit
  def edit
  end

  # GET /recommendations/2/friendProfile
  def friendProfile
    #logger.debug params
    @friend = User.find(params[:recommendation_id])
    @recommendations = Recommendation.get_my_recommedation(params[:recommendation_id])
    @fbId = params[:fbId]
  end

  # GET /recommendations/newsFeed
  def newsFeed
    # show friends recommendation
    @recommendations = Recommendation.get_friend_recommedations(@registered_friends)

    @friend_recommendations = []
    @recommendations.each do |recommendation|
      friend = User.find(recommendation.user)
      hash = {:name => friend.full_name, :fb_id => friend.identity.uid, :image => @graph.get_picture(friend.identity.uid),
        :friendId => friend.id }
      @friend_recommendations.push(hash)
    end
    
    logger.debug @recommendations.count
  end

  # POST /recommendations
  # POST /recommendations.json
  def create
    @recommendation = current_user.recommendations.new

    restaurant = Restaurant.where(:yelp_id => params[:recommendation][:yelp_id], :foursquare_id => params[:recommendation][:foursquare_id], :google_id => params[:recommendation][:google_id]).first

    if restaurant.nil?
      restaurant = Restaurant.new(:yelp_id => params[:recommendation][:yelp_id], :foursquare_id => params[:recommendation][:foursquare_id], :google_id => params[:recommendation][:google_id], :name => params[:recommendation][:name], :location => params[:recommendation][:location])
      restaurant.save!
    end

    @recommendation.description = params[:recommendation][:description]
    @recommendation.like = true
    @recommendation.pictures = params[:recommendation][:pictures]
    @recommendation.restaurant_id = restaurant.id

    respond_to do |format|
      if @recommendation.save
        format.html { redirect_to action: "index", notice: 'Recommendation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @recommendation }
      else
        format.html { render action: 'new' }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recommendations/1
  # PATCH/PUT /recommendations/1.json
  def update
    respond_to do |format|
      if @recommendation.update(recommendation_params)
        format.html { redirect_to @recommendation, notice: 'Recommendation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @recommendation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recommendations/1
  # DELETE /recommendations/1.json
  def destroy
    @recommendation.destroy
    respond_to do |format|
      format.html { redirect_to recommendations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recommendation
      @recommendation = Recommendation.find(params[:id])
    end

    def set_friends
      identity = current_user.identity
      @graph = Koala::Facebook::API.new(identity.token)
      @friends = @graph.get_connections("me", "friends")
      friends_ids = []
      @friends.each do |friend|
        friends_ids << friend["id"]
      end

      @registered_friends = Identity.where(:provider => 'facebook') \
                                          .where('uid IN (?)', friends_ids).collect(&:user_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recommendation_params
      params.require(:recommendation).permit(:like, :description, :user_id, :restaurant_id, :restaurant_name, :pictures)
    end
  end

app/helpers/recommendations_helper.rb
module RecommendationsHelper
end

app/views/recommendations/_form.html.haml
/ recommedation modal
%div{:class => "modal fade", :id => "recModal", :tabindex => "-1", :role => "dialog"}
  .modal-dialog
    .modal-content
      .modal-header
        %button{ :type => "button", :class => "close",  :"data-dismiss"=> "modal" } &times;

        %h4.modal-title#myModalLabel Make a recommedation

      .modal-body
        = simple_form_for @recommendation do |f|
          - if @recommendation.errors.any?
            #error_explanation
              %h2= "#{pluralize(@recommendation.errors.count, "error")} prohibited this recommendation from being saved:"
              %ul
                - @recommendation.errors.full_messages.each do |msg|
                  %li= msg

          .field{:style => "display:none;"}
            = f.label :like
            = f.check_box :like, :disabled => true, :checked => true
          .field
            = f.label :description, "Comments"
            = f.text_area :description, :rows => 4, :cols => 60
          .field
            = f.label :pictures
            = f.file_field :pictures

          = f.hidden_field :yelp_id, value: "#{params[:yelp_id]}"
          = f.hidden_field :foursquare_id, value: "#{params[:foursquare_id]}"
          = f.hidden_field :google_id, value: "#{params[:google_id]}"
          = f.hidden_field :name, value: "#{params[:name]}"
          = f.hidden_field :location, value: "#{params[:location]}"

          %hr
          %button{ :type => "button", :class => "btn btn-default", :"data-dismiss" => "modal" } Close
          %button{ :type => "submit", :class => "btn btn-primary", :onClick => "_gaq.push(['_trackEvent', 'Search', 'Review Added', 'From Restaurant Search']);" } Save changes
      / .modal-footer

app/views/recommendations/_show.html.haml
%p#notice= notice

- @recommendations.each_with_index do |recommendation, index|
  .well
    %p
      %b Like:
      %input{:type => "checkbox", :checked => recommendation.like ? true : nil, :disabled => true}
    %p
      %b Description:
      = recommendation.description
    %p
      %b Rated by:
      = link_to "#{@friend_recommendations[index][:name]} <i class=\"fa fa-facebook\"></i>".html_safe, "http://facebook.com/profile.php?id=" + "#{@friend_recommendations[index][:fb_id]}"
    %p
      %b Restaurant:
      = recommendation.restaurant.name

    - if recommendation.pictures.file?
      %p
        = image_tag recommendation.pictures.url

= image_tag "http://s3-media3.ak.yelpcdn.com/assets/2/www/img/3049d7633b6e/developers/reviewsFromYelpRED.gif"
- @reviews.each do |review|
  .well
    / %p
    /   = link_to '<img src="http://s3-media3.ak.yelpcdn.com/assets/2/www/img/3049d7633b6e/developers/reviewsFromYelpRED.gif"/>'.html_safe, @restaurant["url"]
    %p
      %b Description:
      = review["excerpt"]
    %p
      %img{:src => review["rating_image_small_url"]}
    %p
      %b Rated by:
      = link_to review["user"]["name"], "http://www.yelp.com/user_details?userid=#{review["user"]["id"]}"

- if @tips
  %h3= "Foursquare Rating"
  / %h3= "Foursquare Rating = " + "#{@venue["rating"]}"
  - @tips.items.each do |tip|
    .well
      / %p
      /   = link_to '<img src="https://playfoursquare.s3.amazonaws.com/press/logo/poweredByFoursquare_gray.png" width=115/>'.html_safe, @venue['canonicalUrl']
      %p
        %b Description:
        = tip.text
      %p
        %b Likes:
        = tip.likes.count
      %p
        %b Rated by:
        - name = "#{tip.user.firstName}"
        - if tip.user.lastName
          - name = name + " " + "#{tip.user.lastName}"
        = link_to name, "http://www.foursquare.com/user/" + "#{tip.user.id}"

app/views/recommendations/edit.html.haml
%h1 Editing recommendation

= render 'form'

= link_to 'Show', @recommendation
\|
= link_to 'Back', recommendations_path

app/views/recommendations/friendProfile.html.haml
%h1
  = link_to "#{@friend.first_name + @friend.last_name} <i class=\"fa fa-facebook\"></i>".html_safe, "http://facebook.com/profile.php?id=#{@fbId}"
%div#recModalPlaceholder

.well{"align" => "center"}
  - @recommendations.each do |recommendation|
    %table.table.table-striped{:style=>"border: 1px; width: 100%; margin-bottom: 30px"}
      %tr
        %td
          - if recommendation.pictures.file?
            %p
              = image_tag recommendation.pictures.url(:medium)
        %td
          %p
            %b Like:
            %input{:type => "checkbox", :checked => recommendation.like ? true : nil, :disabled => true}
          %p
            %b Description:
            = recommendation.description
          %p
            %b Restaurant:
            = link_to recommendation.restaurant.name, restaurants_recommendations_path(:yelp_id => recommendation.restaurant.yelp_id, :google_id => recommendation.restaurant.google_id, :foursquare_id => recommendation.restaurant.foursquare_id)

          %p
            = link_to 'More details', user_recommendation_path(current_user, recommendation)

          %p
            =link_to 'Like Restaurant', new_recommendation_path(:restaurant_id => recommendation.restaurant.yelp_id, :restaurant_name => recommendation.restaurant.name) , remote: true, "data-toggle" => "modal", "class" => "btn btn-primary", :onClick => "_gaq.push(['_trackEvent', 'Search', 'Review Added', 'From News Feed']);"

app/views/recommendations/index.html.haml
%h1 Listing recommendations
%div#recModalPlaceholder

- @recommendations.each do |recommendation|
  .well{"align" => "center"}
    %p
      %b Like:
      / %input{:type => "checkbox", :checked}
      %input{:type => "checkbox", :checked => recommendation.like ? true : nil, :disabled => true}
      / :selected => recommendation.like,
      / = recommendation.like ? "Liked" : "Didn't like"
    %p
      %b Description:
      = recommendation.description
    %p
      %b Restaurant:
      = link_to recommendation.restaurant.name, restaurant_path(recommendation.restaurant)

    - if recommendation.pictures.file?
      %p
        = image_tag recommendation.pictures.url(:medium)

    %p
      = link_to 'Show', user_recommendation_path(current_user, recommendation)

/ %td= link_to 'Show', recommendation
/ %td= link_to 'Edit', edit_recommendation_path(recommendation)
/ %td= link_to 'Destroy', recommendation, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/recommendations/new.html.haml
%h1 New recommendation

= render 'form'

= link_to 'Back', recommendations_path

app/views/recommendations/new.js.erb
<% if current_user %>
	$("#recModalPlaceholder").html("<%= escape_javascript(render 'form') %>")
	$("#recModal").modal("show")
<% else %>
	window.location.href = "<%= new_user_session_path %>"
<% end %>

app/views/recommendations/newsFeed.html.haml
%h1 News Feed
%div#recModalPlaceholder

- if !@recommendations.empty?
  .well{"align" => "center"}
    - @recommendations.each_with_index do |recommendation, index|
      %table.table.table-striped{:style=>"border: 1px; width: 100%; margin-bottom: 30px"}
        %tr
          %td
            %p
              = image_tag @friend_recommendations[index][:image], :class => "circular"
              = link_to "#{@friend_recommendations[index][:name]}".html_safe, recommendation_friendProfile_path(:recommendation_id => @friend_recommendations[index][:friendId], :fbId => @friend_recommendations[index][:fb_id])
            - if recommendation.pictures.file?
              %p
                = image_tag recommendation.pictures.url(:medium)
          %td
            %p
              %b Like:
              %input{:type => "checkbox", :checked => recommendation.like ? true : nil, :disabled => true}
            %p
              %b Description:
              = recommendation.description
            %p
              %b Restaurant:
              = link_to recommendation.restaurant.name, restaurants_recommendations_path(:yelp_id => recommendation.restaurant.yelp_id, :google_id => recommendation.restaurant.google_id, :foursquare_id => recommendation.restaurant.foursquare_id)
            %p
              = link_to 'More details', user_recommendation_path(current_user, recommendation)

            %p
              =link_to 'Like Restaurant', new_recommendation_path(:restaurant_id => recommendation.restaurant.yelp_id, :restaurant_name => recommendation.restaurant.name) , remote: true, "data-toggle" => "modal", "class" => "btn btn-primary", :onClick => "_gaq.push(['_trackEvent', 'Search', 'Review Added', 'From News Feed']);"

app/views/recommendations/show.html.haml
= render 'show'

app/views/recommendations/show.js.erb
<% if current_user %>
	$("#friendRecModalPlaceholder").html("<%= escape_javascript(render 'show') %>")
	$("#friendRecModal").modal("show")
<% else %>
	window.location.href = "<%= new_user_session_path %>"
<% end %>