config/routes.rb
Foodee::Application.routes.draw do
  resources :recommendations do
    get "friendProfile"
    get "newsFeed"
  end

  resources :restaurants do

  end

  devise_for :users, :controllers => {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users do
    resources :addresses
    resources :recommendations
  end

  resources :home

  get "restaurants/recommendations"
  get "passthrough/index"
  get "welcome/index"
  get "home/index"

  root 'welcome#index'

end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_address, only: [:show, :edit, :update, :destroy]

  # GET /addresses
  # GET /addresses.json
  def index
    @addresses = current_user.addresses.all
  end

  # GET /addresses/1
  # GET /addresses/1.json
  def show
  end

  # GET /addresses/new
  def new
    @address = current_user.addresses.new
  end

  # GET /addresses/1/edit
  def edit
  end

  # POST /addresses
  # POST /addresses.json
  def create
    flag = false

    if !current_user.addresses.any?
      flag = true
    end

    @address = current_user.addresses.new(address_params)
    @address.default = flag

    respond_to do |format|
      if @address.save
        format.html { redirect_to home_index_path, notice: 'Address was successfully created.' }
        format.json { render action: 'show', status: :created, location: home_index_path}
      else
        format.html { render action: 'new' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addresses/1
  # PATCH/PUT /addresses/1.json
  def update
    respond_to do |format|
      if @address.update(address_params)
        format.html { redirect_to  [current_user, @address], notice: 'Address was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @address.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /addresses/1
  # DELETE /addresses/1.json
  def destroy
    @address.destroy
    respond_to do |format|
      format.html { redirect_to user_addresses_url(current_user) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_address
      @address = current_user.addresses.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def address_params
      params.require(:address).permit(:full_address, :default)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/views/addresses/_form.html.haml
.well.well-registration{"align" => "center"}
  %h2 Add a new address
  %hr
  = simple_form_for [current_user, @address] do |f|
    .input-group.input-group-lg
      %span.input-group-addon
        %i.fa.fa-location-arrow
      = f.input :full_address, :label => false, :placeholder => "Enter a location", :input_html => { :id => 'address-input', :class => 'form-control input-lg' }

    %hr
    .actions
      = f.submit 'Continue', :class => 'btn btn-primary btn-lg', :id => 'addressButton', :onClick => "_gaq.push(['_trackEvent', 'Search', 'Address Page', 'Address Added']);"

:coffee
  $("#address-input").geocomplete
    country: "us"

app/views/addresses/edit.html.haml
%h1 Editing address

= render 'form'

= link_to 'Show', [current_user, @address]
\|
= link_to 'Back', user_addresses_path(current_user)

app/views/addresses/index.html.haml
.well.addresses-well
  %h2.addresses-header{"align" => "center"} Listing Addresses
  %ul#addresses-list
    - @addresses.each do |address|
      %li.row
        .col-md-6
          %i.fa.fa-map-marker.fa-2x.pull-left
          %p.address-info= address.full_address
        .col-md-6
          = simple_form_for [current_user, address], :html => { class: 'pull-right' }  do |f|
            = f.input :default, as: :boolean, :label => false, :wrapper => :bootstrap_switch, :input_html => {:class => 'switcher pull-right', :data => {"on-color" => "success", "off-color" => "default", "on-text" => "YES", "off-text" => "NO"}}

      / %td= link_to 'Show', [current_user, address]
      / %td= link_to 'Edit', edit_user_address_path(current_user, address)
      / %td= link_to 'Destroy', [current_user, address], :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Address', new_user_address_path

:coffee
  $(".switcher").bootstrapSwitch();

app/views/addresses/new.html.haml
- title 'New Address'

= render 'form'

app/views/addresses/show.html.haml
%p
  %b Full:
  = @address.full_address
%p
  %b Street:
  = @address.street
%p
  %b City:
  = @address.city
%p
  %b State:
  = @address.state
%p
  %b Latitude:
  = @address.latitude
%p
  %b Longitude:
  = @address.longitude

= link_to 'Edit', edit_user_address_path(current_user, @address)
\|
= link_to 'Back', user_addresses_path(current_user)