config/routes.rb
Foodee::Application.routes.draw do
  resources :recommendations do
    get "friendProfile"
    get "newsFeed"
  end

  resources :restaurants do

  end

  devise_for :users, :controllers => {
    registrations: "users/registrations",
    passwords: "users/passwords",
    omniauth_callbacks: "users/omniauth_callbacks"
  }

  resources :users do
    resources :addresses
    resources :recommendations
  end

  resources :home

  get "restaurants/recommendations"
  get "passthrough/index"
  get "welcome/index"
  get "home/index"

  root 'welcome#index'

end

app/views/layouts/_footer.html.haml
:javascript
	var _gaq = _gaq || [];
	_gaq.push(['_setAccount', 'UA-49929116-1']);
	_gaq.push(['_trackPageview']);

	(function() {
		var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
		ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
		var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
	})();
	
	$("#search-input").geocomplete({ types: ["establishment"], formatted_address: "#{current_user.addresses.first.full_address if current_user}"});

app/views/layouts/_nav.html.haml
%nav.navbar.navbar-default{role: "navigation"}
  .container-fluid
    .navbar-header{:style => 'display: flex;'}
      %button.navbar-toggle{"data-target" => "#main-navbar", "data-toggle" => "collapse", type: "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Foodee", passthrough_index_path, :class => "navbar-brand"
    #main-navbar.collapse.navbar-collapse
      / .navbar-left.col-md-4
      /   .search-form
      /     = simple_form_for :search, :url => restaurants_path, :html => { :method => :get, :class => "navbar-form"} do |f|
      /       .form-group
      /         = f.input :term, :label => false, :placeholder => "Cuisine, restaurant or leave empty to search around you", :input_html => { :id => 'search-input', :class => 'form-control pull-left' }
      /         = f.submit 'Search', :class => 'btn btn-warning pull-left', :style => 'margin-left: 0.5em;', :onClick => "_gaq.push(['_trackEvent', 'Search', 'Search Done', 'Home Search']);"
      %ul.nav.navbar-nav.navbar-right.pull-right
        - if !@homePage && user_signed_in?
          %li
            .search-form
              = simple_form_for :search, :url => restaurants_path, :html => { :method => :get, :class => "navbar-form"} do |f|
                .form-group
                  = f.input :term, :label => false, :placeholder => "Cuisine, restaurant or leave empty to search around you", :input_html => { :id => 'search-input', :class => 'form-control pull-left' }
                  = f.submit 'Search', :class => 'btn btn-warning pull-left', :style => 'margin-left: 0.5em;', :onClick => "_gaq.push(['_trackEvent', 'Search', 'Search Done', 'Home Search']);"
        - if user_signed_in?
          %li.divider-vertical
          %li= link_to "Dashboard", home_index_path
          %li.divider-vertical
          %li= link_to "My Recommendations", recommendations_path, :onClick => "_gaq.push(['_trackEvent', 'Search', 'Review Viewed', 'My Recommendations']);"
          %li.divider-vertical
          %li.hidden-sm.hidden-md.hidden-lg= link_to "Add Address", new_user_address_path(current_user)
          %li.hidden-sm.hidden-md.hidden-lg= link_to "Logout", destroy_user_session_path, method: :delete
          %li.dropdown.visible-sm.visible-md.visible-lg
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              %i.fa.fa-cog
              %b.caret
            %ul.dropdown-menu
              %li.dropdown-header Settings
              %li.divider
              %li= link_to "Account", edit_user_registration_path
              %li= link_to "Addresses", user_addresses_path(current_user)
              %li= link_to "Logout", destroy_user_session_path, method: :delete
          %li.divider-vertical
        - else
          %li.divider-vertical
          %li= link_to "Sign Up", new_user_registration_path
          %li.divider-vertical
          %li= link_to "Log In", new_user_session_path
          %li.divider-vertical

app/views/layouts/_notice.html.haml
- flash.each do |type, message|
  %div{class: "alert #{bootstrap_class_for(type)} alert-dismissable fade in"}
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} ×
    = message

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Foodee - #{yield(:title)}
    %script{src: "http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"}
    = google_webfonts_link_tag :dosis => [500, 600]
    = google_webfonts_link_tag :open_sans => [400]
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
  %body
    %header

    %nav
      = render 'layouts/nav'
    %div.container#main
      = render 'layouts/notice'
      = yield
    %footer
      = render 'layouts/footer'

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %title Foodee - #{yield(:title)}
    %script{src: "http://maps.googleapis.com/maps/api/js?sensor=false&libraries=places"}
    = google_webfonts_link_tag :dosis => [500, 600]
    = google_webfonts_link_tag :open_sans => [400]
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1.0", name: "viewport"}/
  %body
    %header

    %nav
      = render 'layouts/nav'
    %div#main
      = render 'layouts/notice'
      = yield
    %footer
      // = render 'layouts/footer'